general:
  startup_commands: []
gaps:
  inner_gap: "10px"
  outer_gap: { top: "10px", right: "10px", bottom: "10px", left: "10px" }
animations:
  window_open: { enabled: false }
  window_move: { enabled: false }
  window_resize: { enabled: false }
  workspace_switch: { enabled: false }
workspaces:
  - name: "1"
  - name: "2"
keybindings: []
window_rules:
  - commands: ["stay-interactive"]
    match:
      - window_title: { regex: "^Ticket details for" }
stack:
  tab_bar_height: "30px"
  auto_stack:
    - name: "tickets"
      match:
        - window_process: { equals: "TicketDesk" }
          window_title: { regex: "^Ticket details for" }
